hparams:
  seed: 42
  batch_size: 128
  grad_accumulate_every: 1
  lr: 1e-4
  # max_grad_norm: torch.inf
  n_steps: 1000
  use_ema: true
  ema_decay: 0.9999

datamodule:
  _partial_: true
  _target_: data.data_utils.ExperimentDataModule
  dataset_name: mnist
  root: ./data
  image_size: 28
  num_workers: 8

model:
  _target_: models.rf.RectifiedFlow
  channels: 1
  image_size: ${datamodule.image_size}
  logit_normal_sampling_t: true
  net:
    _target_: modules.networks_unet.UNetModel
    in_channels: 1
    out_channels: 1
    channels: 32
    channel_multipliers: [1, 2, 2]
    num_classes: 10
    n_res_block: 1

optimizer:
  _partial_: true
  _target_: bitsandbytes.optim.AdamW8bit
  lr: ${hparams.lr}
  weight_decay: 0.

project_name: flow-experiment

trainer:
  _partial_: true
  _target_: trainer.Trainer
  accelerator:
    _target_: accelerate.Accelerator
    mixed_precision: bf16
    log_with: wandb
  log_dir: ./logs/mnist/rf
  save_and_sample_interval: 1000
  n_per_class: 10
  fid_stats_dir: ./results/mnist
  fid_eval_interval: 1000
  num_fid_samples: 50000